### ISSUE TITLE
HTTP access control (CORS) issues on localhost.

### ISSUE THREAD

**Issue by mate2002** [titoine54/victoria#19]
@FelixMartel  @laci2103 
The application is unable to reach the mock up data from the backend, because of CORS.
The backend must allow CORS for at least localhost.

See: https://stackoverflow.com/a/27149703
Commit: a11e0577eaebacfec7d7a243437a51182fac3915

**Comment by FelixMartel** [comment]
Hello, was the api hosted on a different port when you tested this locally? https://stackoverflow.com/questions/19966707/cors-error-on-same-domain

Once we merge PR https://github.com/titoine54/victoria/pull/18 it should provide a way to host the frontend and the api on the same domain on dev environments.
