### ISSUE TITLE
Moyenne pour chaque compétence/ap invalide

### ISSUE THREAD

**Issue by laci2103** [titoine54/victoria#36]
Je crois que c'est hardcodé.

Veuillez vous référer à ce lien pour un exemple: https://www.google.ca/search?q=peasant&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj4vNn89-HUAhVJ9YMKHdzNB_MQ_AUICigB&biw=1366&bih=662#imgrc=hlMkl3jptGdvSM:

**Comment by mate2002** [comment]
C'est corrigé la
